/* ------------------------------------------------------------------
   Sillon — base éditoriale ("coups de cœur critiques")
   ------------------------------------------------------------------
   C'est LE cœur du projet, à enrichir dans le temps.
   Chaque style regroupe des artistes de référence, mêlant
   CLASSIQUES ("anciens") et découvertes RÉCENTES, dans l'esprit
   des sélections d'une rédaction musicale (Télérama, Le Monde...).

   ⚠️  RÈGLE ANTI-FAUSSE-ATTRIBUTION : une source presse ne s'affiche QUE
   si l'artiste a un lien d'ARTICLE RÉEL et vérifié (champ `critique`).
   Aucun lien de recherche n'est généré. Sans `critique` → aucune source.

   Champ optionnel par artiste — n'ajouter qu'après avoir ouvert l'URL
   et confirmé qu'elle répond (200) ET parle bien de cet artiste :
     { nom: "...", ere: "recent", critique: {
         rollingstone: "https://www.rollingstone.com/music/music-album-reviews/....",
         telerama:     "https://www.telerama.fr/musique/....",
         lemonde:      "https://www.lemonde.fr/musiques/article/...."
     }}
   On ne recopie JAMAIS le texte des critiques (droit d'auteur).
------------------------------------------------------------------ */

export const STYLES = [
  {
    id: "jazz",
    label: "Jazz",
    emoji: "🎷",
    artistes: [
      { nom: "Miles Davis",         ere: "classique" },
      { nom: "John Coltrane",       ere: "classique" },
      { nom: "Bill Evans",          ere: "classique" },
      { nom: "Thelonious Monk",     ere: "classique" },
      { nom: "Charles Mingus",      ere: "classique" },
      { nom: "Ella Fitzgerald",     ere: "classique" },
      { nom: "Herbie Hancock",      ere: "classique" },
      { nom: "Kamasi Washington",   ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/review-kamasi-washingtons-new-heaven-and-earth-is-another-sprawling-style-hopping-epic-666052/" } },
      { nom: "GoGo Penguin",        ere: "recent" },
      { nom: "Nubya Garcia",        ere: "recent", critique: { nme: "https://www.nme.com/reviews/album/nubya-garcia-source-review-radar-2733238" } },
      { nom: "Robert Glasper",      ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/robert-glasper-delves-into-that-rb-shit-in-search-of-hope-and-solace-on-black-radio-iii-1313013/" } },
      { nom: "Shabaka Hutchings",   ere: "recent" },
      { nom: "Yussef Dayes",        ere: "recent" },
      { nom: "Ezra Collective",     ere: "recent" },
    ],
  },
  {
    id: "rock",
    label: "Rock",
    emoji: "🎸",
    artistes: [
      { nom: "The Velvet Underground", ere: "classique" },
      { nom: "David Bowie",            ere: "classique" },
      { nom: "Radiohead",              ere: "classique", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/a-moon-shaped-pool-202854/" } },
      { nom: "Led Zeppelin",           ere: "classique" },
      { nom: "The Clash",              ere: "classique" },
      { nom: "Pixies",                 ere: "classique" },
      { nom: "Sonic Youth",            ere: "classique" },
      { nom: "Fontaines D.C.",         ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/fontaines-dc-romance-review-1235085815/" } },
      { nom: "IDLES",                  ere: "recent", critique: { nme: "https://www.nme.com/reviews/idles-joy-act-resistance-review-2372527" } },
      { nom: "Big Thief",              ere: "recent" },
      { nom: "King Gizzard & The Lizard Wizard", ere: "recent", critique: { nme: "https://www.nme.com/reviews/album/king-gizzard-the-lizard-wizard-butterfly-3000-review-2966009" } },
      { nom: "Wet Leg",                ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/wet-legs-wet-leg-1333240/" } },
      { nom: "black midi",             ere: "recent", critique: { nme: "https://www.nme.com/reviews/album/black-midi-cavalcade-review-2947430" } },
      { nom: "Black Country, New Road", ere: "recent", critique: { nme: "https://www.nme.com/reviews/album/black-country-new-road-ants-from-up-there-review-3149019" } },
    ],
  },
  {
    id: "hiphop",
    label: "Hip-Hop / Rap",
    emoji: "🎤",
    artistes: [
      { nom: "A Tribe Called Quest", ere: "classique" },
      { nom: "Nas",                  ere: "classique", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/nass-kings-disease-1050630/" } },
      { nom: "Wu-Tang Clan",         ere: "classique" },
      { nom: "J Dilla",              ere: "classique" },
      { nom: "OutKast",              ere: "classique" },
      { nom: "MF DOOM",              ere: "classique" },
      { nom: "Kendrick Lamar",       ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/review-kendrick-lamar-moves-from-uplift-to-beast-mode-on-dazzling-damn-112650/" } },
      { nom: "Little Simz",          ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/little-simz-no-thank-you-1234646675/" } },
      { nom: "Tyler, The Creator",   ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/tyler-the-creator-igor-review-837811/" } },
      { nom: "Denzel Curry",         ere: "recent", critique: { nme: "https://www.nme.com/reviews/album/denzel-curry-melt-your-eyes-see-your-future-album-review-3188487" } },
      { nom: "JID",                  ere: "recent" },
      { nom: "Danny Brown",          ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/review-danny-browns-atrocity-exhibition-is-an-awesome-bummed-out-party-104845/" } },
      { nom: "Freddie Gibbs",        ere: "recent" },
    ],
  },
  {
    id: "rap-fr",
    label: "Rap FR",
    emoji: "🇫🇷",
    artistes: [
      { nom: "IAM",         ere: "classique" },
      { nom: "NTM",         ere: "classique" },
      { nom: "Oxmo Puccino", ere: "classique" },
      { nom: "MC Solaar",   ere: "classique" },
      { nom: "Booba",       ere: "classique" },
      { nom: "PNL",         ere: "recent" },
      { nom: "Alpha Wann",  ere: "recent" },
      { nom: "Nekfeu",      ere: "recent" },
      { nom: "Lomepal",     ere: "recent" },
      { nom: "Laylow",      ere: "recent" },
      { nom: "Zola",        ere: "recent" },
      { nom: "Ziak",        ere: "recent" },
    ],
  },
  {
    id: "electro",
    label: "Électro",
    emoji: "🎛️",
    artistes: [
      { nom: "Daft Punk",        ere: "classique" },
      { nom: "Aphex Twin",       ere: "classique" },
      { nom: "Kraftwerk",        ere: "classique" },
      { nom: "Boards of Canada", ere: "classique" },
      { nom: "The Chemical Brothers", ere: "classique" },
      { nom: "Burial",           ere: "classique" },
      { nom: "Jon Hopkins",      ere: "recent" },
      { nom: "Floating Points",  ere: "recent" },
      { nom: "Bonobo",           ere: "recent" },
      { nom: "Overmono",         ere: "recent" },
      { nom: "Four Tet",         ere: "recent" },
      { nom: "Fred again..",     ere: "recent", critique: { nme: "https://www.nme.com/reviews/album/fred-again-actual-life-2-february-2-october-15-2021-review-3097573" } },
      { nom: "Jamie xx",         ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/in-colour-81013/" } },
    ],
  },
  {
    id: "chanson",
    label: "Chanson française",
    emoji: "🎙️",
    artistes: [
      { nom: "Serge Gainsbourg", ere: "classique" },
      { nom: "Barbara",          ere: "classique" },
      { nom: "Jacques Brel",     ere: "classique" },
      { nom: "Françoise Hardy",  ere: "classique" },
      { nom: "Léo Ferré",        ere: "classique" },
      { nom: "Alain Bashung",    ere: "classique" },
      { nom: "Juliette Armanet", ere: "recent" },
      { nom: "Clara Luciani",    ere: "recent" },
      { nom: "Pomme",            ere: "recent" },
      { nom: "Christine and the Queens", ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/review-christine-the-queens-sly-seductive-chris-727661/" } },
      { nom: "Adrien Soleiman",  ere: "recent" },
      { nom: "November Ultra",   ere: "recent" },
      { nom: "Yseult",           ere: "recent" },
    ],
  },
  {
    id: "soul",
    label: "Soul / Funk",
    emoji: "🕺",
    artistes: [
      { nom: "Marvin Gaye",      ere: "classique" },
      { nom: "Stevie Wonder",    ere: "classique" },
      { nom: "Aretha Franklin",  ere: "classique" },
      { nom: "Curtis Mayfield",  ere: "classique" },
      { nom: "James Brown",      ere: "classique" },
      { nom: "Al Green",         ere: "classique" },
      { nom: "Michael Kiwanuka", ere: "recent", critique: { nme: "https://www.nme.com/reviews/michael-kiwanuka-review-2561891" } },
      { nom: "Leon Bridges",     ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/coming-home-202587/" } },
      { nom: "Anderson .Paak",   ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/malibu-195715/" } },
      { nom: "Durand Jones & The Indications", ere: "recent" },
      { nom: "Lianne La Havas",  ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/blood-197264/" } },
      { nom: "Curtis Harding",   ere: "recent" },
    ],
  },
  {
    id: "rnb",
    label: "R&B / Néo-soul",
    emoji: "💫",
    artistes: [
      { nom: "D'Angelo",         ere: "classique", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/black-messiah-112136/" } },
      { nom: "Erykah Badu",      ere: "classique" },
      { nom: "Lauryn Hill",      ere: "classique" },
      { nom: "Maxwell",          ere: "classique" },
      { nom: "Frank Ocean",      ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/review-frank-oceans-blonde-is-a-dizzy-trippy-druggy-marvel-97555/" } },
      { nom: "SZA",              ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/review-sza-sos-review-1234642441/" } },
      { nom: "Solange",          ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/review-solanges-a-seat-at-the-table-walks-softly-speaks-radically-111107/" } },
      { nom: "Cleo Sol",         ere: "recent" },
      { nom: "Steve Lacy",       ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/review-steve-lacys-gemini-rights-1378646/" } },
      { nom: "Sault",            ere: "recent" },
      { nom: "Snoh Aalegra",     ere: "recent" },
    ],
  },
  {
    id: "classique",
    label: "Classique",
    emoji: "🎻",
    artistes: [
      { nom: "Johann Sebastian Bach", ere: "classique" },
      { nom: "Claude Debussy",        ere: "classique" },
      { nom: "Frédéric Chopin",       ere: "classique" },
      { nom: "Ludwig van Beethoven",  ere: "classique" },
      { nom: "Erik Satie",            ere: "classique" },
      { nom: "Arvo Pärt",             ere: "classique" },
      { nom: "Víkingur Ólafsson",     ere: "recent" },
      { nom: "Hélène Grimaud",        ere: "recent" },
      { nom: "Max Richter",           ere: "recent" },
      { nom: "Ludovico Einaudi",      ere: "recent" },
      { nom: "Hania Rani",            ere: "recent" },
      { nom: "Nils Frahm",            ere: "recent" },
    ],
  },
  {
    id: "folk",
    label: "Folk / Songwriter",
    emoji: "🪕",
    artistes: [
      { nom: "Bob Dylan",         ere: "classique", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/bob-dylan-rough-rowdy-ways-1015086/" } },
      { nom: "Leonard Cohen",     ere: "classique" },
      { nom: "Joni Mitchell",     ere: "classique" },
      { nom: "Nick Drake",        ere: "classique" },
      { nom: "Neil Young",        ere: "classique", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/neil-young-and-crazy-horse-colorado-905860/" } },
      { nom: "Fleet Foxes",       ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/review-fleet-foxes-up-their-prog-game-on-epic-crack-up-200998/" } },
      { nom: "Bon Iver",          ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/review-bon-ivers-22-a-million-brings-futurism-to-justin-vernons-cabin-128519/" } },
      { nom: "Sufjan Stevens",    ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/carrie-lowell-113010/" } },
      { nom: "Phoebe Bridgers",   ere: "recent" },
      { nom: "Weyes Blood",       ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/review-weyes-bloods-titanic-rising-818302/" } },
      { nom: "Adrianne Lenker",   ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/adrianne-lenkers-songs-1083775/" } },
    ],
  },
  {
    id: "afro",
    label: "Afro / World",
    emoji: "🌍",
    artistes: [
      { nom: "Fela Kuti",        ere: "classique" },
      { nom: "Ali Farka Touré",  ere: "classique" },
      { nom: "Tinariwen",        ere: "classique" },
      { nom: "Amadou & Mariam",  ere: "classique" },
      { nom: "Cesária Évora",    ere: "classique" },
      { nom: "Burna Boy",        ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/review-burna-boy-love-damini-1377950/" } },
      { nom: "Angélique Kidjo",  ere: "recent" },
      { nom: "Fatoumata Diawara",ere: "recent" },
      { nom: "Ibrahim Maalouf",  ere: "recent" },
      { nom: "Wizkid",           ere: "recent", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/review-wizkid-more-love-less-ego-1234617419/" } },
      { nom: "Songhoy Blues",    ere: "recent" },
    ],
  },
  {
    id: "metal",
    label: "Métal / Post-rock",
    emoji: "🤘",
    artistes: [
      { nom: "Black Sabbath",    ere: "classique" },
      { nom: "Metallica",        ere: "classique", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/metallica-72-seasons-1234708231/" } },
      { nom: "Tool",             ere: "classique", critique: { rollingstone: "https://www.rollingstone.com/music/music-album-reviews/review-tool-return-from-a-long-hiatus-with-fear-inoculum-879842/" } },
      { nom: "Godspeed You! Black Emperor", ere: "classique" },
      { nom: "Mogwai",           ere: "classique" },
      { nom: "Gojira",           ere: "recent", critique: { nme: "https://www.nme.com/reviews/album/gojira-fortitude-review-2928116" } },
      { nom: "Deafheaven",       ere: "recent" },
      { nom: "Sleep Token",      ere: "recent", critique: { nme: "https://www.nme.com/reviews/album/sleep-token-take-me-back-to-eden-review-3444788" } },
      { nom: "Explosions in the Sky", ere: "recent" },
      { nom: "Igorrr",           ere: "recent" },
    ],
  },
];
