/* ------------------------------------------------------------------
   Sillon — base éditoriale ("coups de cœur critiques")
   ------------------------------------------------------------------
   C'est LE cœur du projet, à enrichir dans le temps.
   Chaque style regroupe des artistes de référence, mêlant
   CLASSIQUES ("anciens") et découvertes RÉCENTES, dans l'esprit
   des sélections d'une rédaction musicale (Télérama, Le Monde...).

   ⚠️  On ne recopie AUCUN texte de critique. Par défaut, chaque carte
   propose un lien de RECHERCHE de l'artiste sur Télérama et Le Monde
   (généré automatiquement — réel, jamais inventé).

   Champ optionnel par artiste, si vous trouvez UN article précis à citer :
     { nom: "...", ere: "recent", critique: {
         telerama: "https://www.telerama.fr/musique/....",
         lemonde:  "https://www.lemonde.fr/musiques/article/...."
     }}
   Renseigné → la carte pointe vers l'article ; sinon → recherche par défaut.
------------------------------------------------------------------ */

export const STYLES = [
  {
    id: "jazz",
    label: "Jazz",
    emoji: "🎷",
    artistes: [
      { nom: "Miles Davis",         ere: "classique" },
      { nom: "John Coltrane",       ere: "classique" },
      { nom: "Bill Evans",          ere: "classique" },
      { nom: "Thelonious Monk",     ere: "classique" },
      { nom: "Charles Mingus",      ere: "classique" },
      { nom: "Ella Fitzgerald",     ere: "classique" },
      { nom: "Herbie Hancock",      ere: "classique" },
      { nom: "Kamasi Washington",   ere: "recent" },
      { nom: "GoGo Penguin",        ere: "recent" },
      { nom: "Nubya Garcia",        ere: "recent" },
      { nom: "Robert Glasper",      ere: "recent" },
      { nom: "Shabaka Hutchings",   ere: "recent" },
      { nom: "Yussef Dayes",        ere: "recent" },
      { nom: "Ezra Collective",     ere: "recent" },
    ],
  },
  {
    id: "rock",
    label: "Rock",
    emoji: "🎸",
    artistes: [
      { nom: "The Velvet Underground", ere: "classique" },
      { nom: "David Bowie",            ere: "classique" },
      { nom: "Radiohead",              ere: "classique" },
      { nom: "Led Zeppelin",           ere: "classique" },
      { nom: "The Clash",              ere: "classique" },
      { nom: "Pixies",                 ere: "classique" },
      { nom: "Sonic Youth",            ere: "classique" },
      { nom: "Fontaines D.C.",         ere: "recent" },
      { nom: "IDLES",                  ere: "recent" },
      { nom: "Big Thief",              ere: "recent" },
      { nom: "King Gizzard & The Lizard Wizard", ere: "recent" },
      { nom: "Wet Leg",                ere: "recent" },
      { nom: "black midi",             ere: "recent" },
      { nom: "Black Country, New Road", ere: "recent" },
    ],
  },
  {
    id: "hiphop",
    label: "Hip-Hop / Rap",
    emoji: "🎤",
    artistes: [
      { nom: "A Tribe Called Quest", ere: "classique" },
      { nom: "Nas",                  ere: "classique" },
      { nom: "Wu-Tang Clan",         ere: "classique" },
      { nom: "J Dilla",              ere: "classique" },
      { nom: "OutKast",              ere: "classique" },
      { nom: "MF DOOM",              ere: "classique" },
      { nom: "Kendrick Lamar",       ere: "recent" },
      { nom: "Little Simz",          ere: "recent" },
      { nom: "Tyler, The Creator",   ere: "recent" },
      { nom: "Denzel Curry",         ere: "recent" },
      { nom: "JID",                  ere: "recent" },
      { nom: "Danny Brown",          ere: "recent" },
      { nom: "Freddie Gibbs",        ere: "recent" },
    ],
  },
  {
    id: "rap-fr",
    label: "Rap FR",
    emoji: "🇫🇷",
    artistes: [
      { nom: "IAM",         ere: "classique" },
      { nom: "NTM",         ere: "classique" },
      { nom: "Oxmo Puccino", ere: "classique" },
      { nom: "MC Solaar",   ere: "classique" },
      { nom: "Booba",       ere: "classique" },
      { nom: "PNL",         ere: "recent" },
      { nom: "Alpha Wann",  ere: "recent" },
      { nom: "Nekfeu",      ere: "recent" },
      { nom: "Lomepal",     ere: "recent" },
      { nom: "Laylow",      ere: "recent" },
      { nom: "Zola",        ere: "recent" },
      { nom: "Ziak",        ere: "recent" },
    ],
  },
  {
    id: "electro",
    label: "Électro",
    emoji: "🎛️",
    artistes: [
      { nom: "Daft Punk",        ere: "classique" },
      { nom: "Aphex Twin",       ere: "classique" },
      { nom: "Kraftwerk",        ere: "classique" },
      { nom: "Boards of Canada", ere: "classique" },
      { nom: "The Chemical Brothers", ere: "classique" },
      { nom: "Burial",           ere: "classique" },
      { nom: "Jon Hopkins",      ere: "recent" },
      { nom: "Floating Points",  ere: "recent" },
      { nom: "Bonobo",           ere: "recent" },
      { nom: "Overmono",         ere: "recent" },
      { nom: "Four Tet",         ere: "recent" },
      { nom: "Fred again..",     ere: "recent" },
      { nom: "Jamie xx",         ere: "recent" },
    ],
  },
  {
    id: "chanson",
    label: "Chanson française",
    emoji: "🎙️",
    artistes: [
      { nom: "Serge Gainsbourg", ere: "classique" },
      { nom: "Barbara",          ere: "classique" },
      { nom: "Jacques Brel",     ere: "classique" },
      { nom: "Françoise Hardy",  ere: "classique" },
      { nom: "Léo Ferré",        ere: "classique" },
      { nom: "Alain Bashung",    ere: "classique" },
      { nom: "Juliette Armanet", ere: "recent" },
      { nom: "Clara Luciani",    ere: "recent" },
      { nom: "Pomme",            ere: "recent" },
      { nom: "Christine and the Queens", ere: "recent" },
      { nom: "Adrien Soleiman",  ere: "recent" },
      { nom: "November Ultra",   ere: "recent" },
      { nom: "Yseult",           ere: "recent" },
    ],
  },
  {
    id: "soul",
    label: "Soul / Funk",
    emoji: "🕺",
    artistes: [
      { nom: "Marvin Gaye",      ere: "classique" },
      { nom: "Stevie Wonder",    ere: "classique" },
      { nom: "Aretha Franklin",  ere: "classique" },
      { nom: "Curtis Mayfield",  ere: "classique" },
      { nom: "James Brown",      ere: "classique" },
      { nom: "Al Green",         ere: "classique" },
      { nom: "Michael Kiwanuka", ere: "recent" },
      { nom: "Leon Bridges",     ere: "recent" },
      { nom: "Anderson .Paak",   ere: "recent" },
      { nom: "Durand Jones & The Indications", ere: "recent" },
      { nom: "Lianne La Havas",  ere: "recent" },
      { nom: "Curtis Harding",   ere: "recent" },
    ],
  },
  {
    id: "rnb",
    label: "R&B / Néo-soul",
    emoji: "💫",
    artistes: [
      { nom: "D'Angelo",         ere: "classique" },
      { nom: "Erykah Badu",      ere: "classique" },
      { nom: "Lauryn Hill",      ere: "classique" },
      { nom: "Maxwell",          ere: "classique" },
      { nom: "Frank Ocean",      ere: "recent" },
      { nom: "SZA",              ere: "recent" },
      { nom: "Solange",          ere: "recent" },
      { nom: "Cleo Sol",         ere: "recent" },
      { nom: "Steve Lacy",       ere: "recent" },
      { nom: "Sault",            ere: "recent" },
      { nom: "Snoh Aalegra",     ere: "recent" },
    ],
  },
  {
    id: "classique",
    label: "Classique",
    emoji: "🎻",
    artistes: [
      { nom: "Johann Sebastian Bach", ere: "classique" },
      { nom: "Claude Debussy",        ere: "classique" },
      { nom: "Frédéric Chopin",       ere: "classique" },
      { nom: "Ludwig van Beethoven",  ere: "classique" },
      { nom: "Erik Satie",            ere: "classique" },
      { nom: "Arvo Pärt",             ere: "classique" },
      { nom: "Víkingur Ólafsson",     ere: "recent" },
      { nom: "Hélène Grimaud",        ere: "recent" },
      { nom: "Max Richter",           ere: "recent" },
      { nom: "Ludovico Einaudi",      ere: "recent" },
      { nom: "Hania Rani",            ere: "recent" },
      { nom: "Nils Frahm",            ere: "recent" },
    ],
  },
  {
    id: "folk",
    label: "Folk / Songwriter",
    emoji: "🪕",
    artistes: [
      { nom: "Bob Dylan",         ere: "classique" },
      { nom: "Leonard Cohen",     ere: "classique" },
      { nom: "Joni Mitchell",     ere: "classique" },
      { nom: "Nick Drake",        ere: "classique" },
      { nom: "Neil Young",        ere: "classique" },
      { nom: "Fleet Foxes",       ere: "recent" },
      { nom: "Bon Iver",          ere: "recent" },
      { nom: "Sufjan Stevens",    ere: "recent" },
      { nom: "Phoebe Bridgers",   ere: "recent" },
      { nom: "Weyes Blood",       ere: "recent" },
      { nom: "Adrianne Lenker",   ere: "recent" },
    ],
  },
  {
    id: "afro",
    label: "Afro / World",
    emoji: "🌍",
    artistes: [
      { nom: "Fela Kuti",        ere: "classique" },
      { nom: "Ali Farka Touré",  ere: "classique" },
      { nom: "Tinariwen",        ere: "classique" },
      { nom: "Amadou & Mariam",  ere: "classique" },
      { nom: "Cesária Évora",    ere: "classique" },
      { nom: "Burna Boy",        ere: "recent" },
      { nom: "Angélique Kidjo",  ere: "recent" },
      { nom: "Fatoumata Diawara",ere: "recent" },
      { nom: "Ibrahim Maalouf",  ere: "recent" },
      { nom: "Wizkid",           ere: "recent" },
      { nom: "Songhoy Blues",    ere: "recent" },
    ],
  },
  {
    id: "metal",
    label: "Métal / Post-rock",
    emoji: "🤘",
    artistes: [
      { nom: "Black Sabbath",    ere: "classique" },
      { nom: "Metallica",        ere: "classique" },
      { nom: "Tool",             ere: "classique" },
      { nom: "Godspeed You! Black Emperor", ere: "classique" },
      { nom: "Mogwai",           ere: "classique" },
      { nom: "Gojira",           ere: "recent" },
      { nom: "Deafheaven",       ere: "recent" },
      { nom: "Sleep Token",      ere: "recent" },
      { nom: "Explosions in the Sky", ere: "recent" },
      { nom: "Igorrr",           ere: "recent" },
    ],
  },
];
